[theme]
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
runOnSave = true
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "minimal"

[layout]
wideMode = true
