
[theme]
base="light"
primaryColor="#f63366"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#262730"
font="sans serif"

[server]
headless = true
enableCORS = false
port = 8501

[client]
toolbarMode = "minimal"
